name: Deploy

on:
  push:
    branches: [ france-elections-experimental ]

jobs:
  test:
    uses: "ambanum/OpenTermsArchive/.github/workflows/test.yml@france-elections-experimental"
  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.SERVER_FINGERPRINT }}
      - run: echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > vault.key
      - run: pip install --upgrade setuptools
      - run: pip install 'ansible ~= 2.9'
      - run: ansible-playbook ops/site.yml --inventory ops/inventories/production.yml
